spring:
  cloud:
    aws:
      credentials:
        access-key: ANUJDEKAVADIYAEXAMPLE   # localstack credentials
        secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY # localstack credentials
      endpoint:
        uri: http://localhost:4566

  datasource:
    url: jdbc:postgresql://localhost:5432/document_processor
    username: postgres
    password: Homemaranha123@
    driver-class-name: org.postgresql.Driver