spring:
  application:
    name: document-processor

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /document-processor

